### ISSUE TITLE
Feriados 2017

### ISSUE THREAD

**Issue by Josecanalla** [pjnovas/nolaborables#10]
Buenas, quería saber si el proyecto sigue en pie y si van a cargar los feriados del 2017. Vengo usando esta API y me resulta muy útil!

Saludos.

**Comment by pjnovas** [comment]
@Josecanalla si!, estoy esperando que se aprueben porque todavía no están listos desde el [Ministerio del Interior](http://www.mininterior.gov.ar/tramitesyservicios/feriados.php)

Si vas al 2017 aparece el siguiente mensaje:
> IMPORTANTE: El proyecto de ley para regular los feriados 2017 fue enviado por el Poder Ejecutivo al Congreso de la Nación y se encuentra en tratamiento.
