### ISSUE TITLE
Solapamiento de Feriados

### ISSUE THREAD

**Issue by walterdobro** [pjnovas/nolaborables#15]
Cuando hay 2 feriados el mismo día, la API solo muestra uno de ellos y no ambos.

Ejemplo:
En el año 2018, viernes santo cae el mismo día que uno de las pascuas judías.
https://github.com/pjnovas/nolaborables/blob/master/lib/data/holidays/2018.json
```
{
  "mes": "marzo",
  "24": "memoria-verdad-justicia",
  "29": "jueves-santo",
  "30": "viernes-santo",
  "30,31": "pascuas-judias"
}
```

Al ejecutar http://nolaborables.com.ar/api/v2/feriados/2018 o http://nolaborables.com.ar/api/v2/feriados/2018?incluir=opcional no devuelve el viernes santo en ningún caso y debería devolverlo en ambos.

**Comment by pjnovas** [comment]
@walterdobro arreglado y deployado, cualquier cosa avisa.
Gracias por el reporte!
