### ISSUE TITLE
Consistencia con sitio del ministerio - feriados 2019

### ISSUE THREAD

**Issue by Ambro17** [pjnovas/nolaborables#16]
Hola, primero que nada felicitaciones por este desarrollo. Espero que el proyecto siga vivo. 

Llegué acá porque actualmente estoy parseando el sitio https://www.argentina.gob.ar/interior/feriados para obtener los feriados, pero le pusieron una comprobación extra que exige que el cliente tenga habilitado js que rompió mi script, con lo cual me parece buena idea empezar a usar esta api y consumir datos en un formato más consistente. 

A la hora de comparar los resultados de la API con los del sitio del ministerio encontré algunas -pocas- diferencias. A saber:
`17-06-2019`. En el ministerio figura trasladable. La api lo devuelve como `nolaborable`
`31-08-2019`. En el ministerio figura no laborable por 'Año Nuevo Islámico'. La api no lo tiene registrado como feriado ese día sino el `11-09-2019`. El día correcto según una rápida búsqueda en google es el `31-08-2019`, como dice el sitio del ministerio.

Gracias de antemano, no tengo problema en agregarlos yo si me explicás el proceso o de donde parseas los datos.
Saludos o/

**Comment by pjnovas** [comment]
@Ambro17 gracias por reportar los errores y por el PR!, ya estan deployados los cambios. saludos!
