### ISSUE TITLE
Feriado no actualizado del 2/4/2020 al 31/3/2020

### ISSUE THREAD

**Issue by NeoEGM** [pjnovas/nolaborables#22]
Con motivos del DNU dictado por el Presidente, el feriado inamovible del 2/4/2020 fue trasladado por única vez al 31/3/2020.

Esto no se vio reflejado en la base de datos.

Este sería el día tal como está ahora:

```php
263 => 
array (
	'motivo' => 'Día del Veterano y de los Caídos en la Guerra de Malvinas',
	'tipo' => 1,
	'dia' => 2,
	'mes' => 4,
	'id' => 'veteranos-malvinas',
	'año' => 2020,
	'fecha' => '2020-04-02',
	'tipo_new' => 'inamovible',
	'descripcion' => 'Día del Veterano y de los Caídos en la Guerra de Malvinas',
),
```

Y así debería figurar:

```php
263 => 
array (
	'motivo' => 'Día del Veterano y de los Caídos en la Guerra de Malvinas (Trasladado)',
	'tipo' => 1,
	'dia' => 31,
	'mes' => 3,
	'id' => 'veteranos-malvinas',
	'año' => 2020,
	'fecha' => '2020-03-31',
	'tipo_new' => 'inamovible',
	'descripcion' => 'Día del Veterano y de los Caídos en la Guerra de Malvinas (Trasladado)',
	'original' => '2020-04-02',
),
```

Sigue en mantenimiento este proyecto o ya fue dejado de lado?

Muchas gracias!

Saludos!

Ezequiel.

**Comment by pjnovas** [comment]
Buenas!, ahí lo actualicé, gracias por avisar. 😄 

La API sigue en mantenimiento, no estoy muy pendiente de los feriados pero si del repo por lo q una PR la puedo ver al toque, mergear y deployar 😉 

La [data de la api está en formato JSON en este mismo repo](https://github.com/pjnovas/nolaborables/tree/master/lib/data/holidays) por lo que se puede actualizar mandando una PR directamente, [el commit de este cambio como referencia](https://github.com/pjnovas/nolaborables/commit/3f98884706ba7afe358636e0ffa7190db78b7636)

[Próximo Feriado](https://codepen.io/pjnovas/pen/apJXrr)

Saludos!

**Comment by NeoEGM** [comment]
Muchas gracias Pablo! Lo tengo en cuenta para la próxima!
Saludos!!
Ezequiel.
