### ISSUE TITLE
Soporte para próximos años.

### ISSUE THREAD

**Issue by pazguille** [pjnovas/nolaborables#26]
Quería saber si te interesa sumar soporte para responder con los feriados básicos de un año no cargado en lugar de tirar un error, dado que hay feriados que posiblemente no cambien y te permiten tener una idea. Una vez definido los feriados de ese año se crearía el file correspondiente y listo. Podríamos usar este `base` para armarlo más dinámico.

**Comment by pjnovas** [comment]
dale, suena piola. Ahora lo armo ;)

**Comment by pazguille** [comment]
Tengo algo para mandar PR :P

Slds,

Guille Paz
https://pazguille.me

**Comment by pjnovas** [comment]
ahh dale, mandá nomas entonces

**Comment by pazguille** [comment]
#28
