### ISSUE TITLE
Ofrecer un link para más información en cada feriado.

### ISSUE THREAD

**Issue by pazguille** [pjnovas/nolaborables#29]
Sumar a `ref.json` un link a wikipedia en cada feriado  para poder ofrecer más info.

Ejemplo:
```
{
  "año-nuevo": {
    "motivo": "Año Nuevo",
    "tipo": "inamovible",
    "wiki": "https://es.wikipedia.org/wiki/A%C3%B1o_Nuevo"
  },
  "memoria-verdad-justicia": {
    "motivo": "Día Nacional de la Memoria por la Verdad y la Justicia",
    "tipo": "inamovible",
    "wiki": "https://es.wikipedia.org/wiki/D%C3%ADa_Nacional_de_la_Memoria_por_la_Verdad_y_la_Justicia"
  },
  "veteranos-malvinas": {
    "motivo": "Día del Veterano y de los Caídos en la Guerra de Malvinas",
    "tipo": "inamovible",
    "wiki":  "https://es.wikipedia.org/wiki/D%C3%ADa_del_Veterano_y_de_los_Ca%C3%ADdos_en_la_Guerra_de_Malvinas"
  },
}
```

Si es de interes armo PR.

NOTA: Puse  `wiki` a modo de referencia, puede ser el que mejor te parezca.

Gracias!

**Comment by pjnovas** [comment]
seee, en un momento se estuvo hablando de sumar el decreto también, pero un link de referencia histórica es suena copado de tener

**Comment by pjnovas** [comment]
deployado!, @pazguille no es necesario mantener la version 1, la dejé solo porque parece que hay algunos legacy q la usan pero no es necesario darle nuevas funcionalidades, con que no se rompa estamos bien ;)

Gracias por el aporte!
