### ISSUE TITLE
Error con años futuros

### ISSUE THREAD

**Issue by juanblasmdq** [pjnovas/nolaborables#37]
Pablo, primero que nada, gracias por tomarte el tiempo de armar esta estupenda API

Estoy hace un par de días usándola y sin querer encontré un error; si uno ingresa años futuros, retorna los feriados del último año

Por ejemplo probé https://nolaborables.com.ar/api/v2/feriados/222222 y me trajo un json con los feriados del 2021

Espero el dato sirva

Sds!

**Comment by pjnovas** [comment]
buenas, es un esperado, en vez de retornar un 404 retorna los feriados inamovibles de todos los años, fíjate que no son todos los de este año.

saludos
