### ISSUE TITLE
Hoy (09/08/2022) me dejó de funcionar

### ISSUE THREAD

**Issue by jmquintana** [pjnovas/nolaborables#43]
Dejó de funcionar la API el día de hoy.

¿Será definitivo?

**Comment by pjnovas** [comment]
buenas, si, se venció el dominio, lo renové hace unas horas, hay que esperar a que actualicen los DNS.

**Comment by jmquintana** [comment]
aaah! buenisimo! gracias! avisa y te invito un cafecito! ;)

**Comment by jmquintana** [comment]
ya funciona! 😊
